application: mzcompare
version: 0-4-3-b
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /tasks/teams_update
  script: update.py
  login: admin

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /humans.txt
  static_files: humans.txt
  upload: humans.txt

- url: /static
  static_dir: static

- url: /.*
  script: main.py